name: Generate Release Info

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  admin-docs:
    name: "Trigger admin schema build for stoplight"
    if: "!github.event.release.prerelease"
    uses: Isengo1989/admin-api-reference/.github/workflows/base_schema.yml@main
    with:
      shopware_version: ${{ github.event.release.tag_name }}
